[package]
name = "open-gala"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
clap = { version = "4.3.21", features = ["derive"] }
confy = "0.5.1"
cookie = "0.10"
csv = "1.2.2"
directories = "5.0.1"
futures = "0.3.28"
lazy_static = "1.4.0"
os_path = "0.6.3"
reqwest = { version = "0.11.18", features = ["json", "cookies", "rustls-tls"] }
rpassword = "7.2.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
time = "0.1"
tokio = { version = "1.31.0", features = ["full"] }
